trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: SonarQubePrepare@5
  inputs:
    SonarQube: 'SonarQube'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'IngSoftware'
    cliProjectName: 'IngSoftware'
    cliSources: '.'

- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    yarn install
  displayName: 'yarn install'

- script: |
    yarn build
  displayName: 'yarn build'

- script: |
    yarn test --ci --reporters=jest-junit --outputFile=jest-results/junit.xml
  displayName: 'Run tests and generate JUnit results'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/jest-results/junit.xml'
    failTaskOnFailedTests: true

- task: SonarQubeAnalyze@5

- task: SonarQubePublish@5
  inputs:
    pollingTimeoutSec: '300'
